version: "3.9"
services:
  auth_service:
    build: .
    ports:
      - 9443:9443
  auth-db:
    container_name: localdb
    image: "postgres:15.2-alpine"
    restart: unless-stopped
    user: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - "./postgresData:/data/postgres"

volumes:
  postgresData:
